const CATEGORIES = [
    ["Günstig","Teuer"],
    ["Leicht","Schwer"],
    ["Klein","Groß"],
    ["Kurz","Lang"],
    ["Langsam","Schnell"],
    ["Leise","Laut"],
    ["Schwach","Stark"],
    ["Kalt","Heiß"],
    ["Weich","Hart"],
    ["Süß","Sauer"],
    ["Einfach","Komplex"],
    ["Alt","Neu"],
    ["Glatt","Rau"],
    ["Leicht verständlich","Schwer verständlich"],
    ["Langweilig","Spannend"],
    ["Sauber","Schmutzig"],
    ["Dünn","Dick"],
    ["Matt","Scharf"],
    ["Zerbrechlich","Robust"],
    ["Dunkel","Hell"],
    ["Ruhig","Unruhig"],
    ["Niedrig","Hoch"],
    ["Wenig","Viel"],
    ["Schlicht","Elegant"],
    ["Mild","Scharf"],
    ["Sparsam","Verschwendungsvoll"],
    ["Wenig Zeit","Viel Zeit"],
    ["Niedrige Qualität","Hohe Qualität"],
    ["Unbeliebt","Beliebt"],
    ["Wenig Zutaten","Viele Zutaten"],
    ["Wenige Farben","Viele Farben"],
    ["Wenig Lärm","Viel Lärm"],
    ["Wenig Geschmack","Viel Geschmack"],
    ["Niedrige Höhe","Hohe Höhe"],
    ["Selten","Häufig"],
    ["Einfach","Verziert"],
    ["Schlicht","Bunt"],
    ["Kurze Lebensdauer","Lange Lebensdauer"],
    ["Kurze Strecke","Lange Strecke"],
    ["Kurze Haare","Lange Haare"],
    ["Niedriger Druck","Hoher Druck"],
    ["Einfache Form","Komplexe Form"],
    ["Kurzlebig","Langlebig"],
    ["Wenige Seiten","Viele Seiten"],
    ["Leichte Aufgabe","Schwere Aufgabe"],
    ["Leichter Geruch","Starker Geruch"],
    ["Wenige Beine","Viele Beine"],
    ["Wenig Zucker","Viel Zucker"],
    ["Locker","Fest"],
    ["Leichte Beleuchtung","Starke Beleuchtung"],
    ["Kurzer Film","Langer Film"],
    ["Kurzer Sport","Langer Sport"],
    ["Wenig beliebt","Stark beliebt"],
    ["Schwacher Wind","Starker Wind"],
    ["Pflegeleicht","Pflegeintensiv"],
    ["Kurze Reise","Lange Reise"],
    ["Leichtes Material","Schweres Material"],
    ["Geringe Temperatur","Hohe Temperatur"],
    ["Mild","Extrem"],
    ["Wenig Koffein","Viel Koffein"],
    ["Einfache Aufgabe","Komplizierte Aufgabe"],
    ["Geringes Risiko","Hohes Risiko"],
    ["Schwacher Magnet","Starker Magnet"],
    ["Dunkler Bildschirm","Heller Bildschirm"],
    ["Leichtes Rätsel","Schweres Rätsel"],
    ["Niedrige Frequenz","Hohe Frequenz"],
    ["Leise Musik","Laute Musik"],
    ["Wenige Räder","Viele Räder"],
    ["Niedrige Leistung","Hohe Leistung"],
    ["Wenig Salz","Viel Salz"],
    ["Schwache Isolierung","Starke Isolierung"],
    ["Geringe Haltbarkeit","Hohe Haltbarkeit"],
    ["Niedriger Sauerstoff","Hoher Sauerstoff"],
    ["Einfaches Rezept","Kompliziertes Rezept"],
    ["Wenig Kreativität","Viel Kreativität"],
    ["Kleines Tier","Großes Tier"],
    ["Billiges Spielzeug","Teures Spielzeug"],
    ["Einfaches Werkzeug","Komplexes Werkzeug"],
    ["Langsames Tier","Schnelles Tier"],
    ["Wenige Knöpfe","Viele Knöpfe"],
    ["Kurzes Lied","Langes Lied"],
    ["Leichte Sprache","Schwere Sprache"],
    ["Kleine Fantasie","Viel Fantasie"],
    ["Kurzes Kunstwerk","Langes Kunstwerk"],
    ["Einfache Aufgabe","Schwere Aufgabe"],
    ["Helles","Licht-Starkes Licht"],
    ["Früh","Spät"],
    ["Leer","Voll"],
    ["Trocken","Nass"],
    ["Locker sitzend","Eng sitzend"],
    ["Wenig Verkehr","Viel Verkehr"],
    ["Kurze Warteschlange","Lange Warteschlange"],
    ["Wenig Regen","Viel Regen"],
    ["Flach","Tief"],
    ["Kurze Akkulaufzeit","Lange Akkulaufzeit"],
    ["Niedrige Auflösung","Hohe Auflösung"],
    ["Einfacher Geschmack","Komplexer Geschmack"],
    ["Leichte Übung","Schwere Übung"],
    ["Komfortabel","Unbequem"],
    ["Niedrige Geschwindigkeit","Hohe Geschwindigkeit"],
    ["Kleiner Hunger","Großer Hunger"],
    ["Wenig Schatten","Viel Schatten"],
    ["Wenig Spannung","Viel Spannung"],
    ["Niedriger Aufwand","Hoher Aufwand"],
    ["Wenig Bewegung","Viel Bewegung"],
    ["Einfaches Spiel","Komplexes Spiel"],
    ["Wenig Hitze","Viel Hitze"],
    ["Geringe Sichtweite","Hohe Sichtweite"],
    ["Wenig Fantasie","Viel Fantasie"],
    ["Wenig Stil","Viel Stil"],
    ["Wenig Farbe","Viel Farbe"],
    ["Wenig Motivation","Viel Motivation"],
    ["Niedrige Temperatur","Hohe Temperatur"],
    ["Wenig Wasser","Viel Wasser"],
    ["Wenig Schnee","Viel Schnee"],
    ["Wenig Wind","Viel Wind"],
    ["Kurzfristig","Langfristig"],
    ["Wenig Wissen","Viel Wissen"],
    ["Wenig Talent","Viel Talent"],
    ["Wenig Humor","Viel Humor"],
    ["Wenig Geschmack","Viel Geschmack"],
    ["Wenig Falten","Viele Falten"],
    ["Geringes Gewicht","Hohes Gewicht"],
    ["Wenig Ausdauer","Viel Ausdauer"],
    ["Wenig Stress","Viel Stress"],
    ["Wenig Technik","Viel Technik"],
    ["Wenig Benzin","Viel Benzin"],
    ["Wenig Fantasie","Viel Fantasie"],
    ["Geringe Gefahr","Hohe Gefahr"],
    ["Wenig Hitze","Viel Hitze"],
    ["Wenig Vertrauen","Viel Vertrauen"],
    ["Kurzes Leben","Langes Leben"],
    ["Geringe Lautstärke","Hohe Lautstärke"],
    ["Wenig Hoffnung","Viel Hoffnung"],
    ["Wenig Struktur","Viel Struktur"],
    ["Wenig Aroma","Viel Aroma"],
    ["Einfacher Stil","Komplizierter Stil"],
    ["Wenig Platz","Viel Platz"],
    ["Wenig Nachfrage","Viel Nachfrage"],
    ["Wenig Angebot","Viel Angebot"],
    ["Geringe Stärke","Hohe Stärke"],
    ["Geringe Wärme","Hohe Wärme"],
    ["Wenig Druck","Viel Druck"],
    ["Wenig Spaß","Viel Spaß"],
    ["Wenig Farbe","Viel Farbe"],
    ["Langsam arbeitend","Schnell arbeitend"],
    ["Geringe Tiefe","Große Tiefe"],
    ["Wenig Glanz","Viel Glanz"],
    ["Wenig Vielfalt","Viel Vielfalt"],
    ["Wenig Textur","Viel Textur"],
    ["Wenig Bewegung","Viel Bewegung"],
    ["Wenig Emotion","Viel Emotion"],
    ["Wenig Klarheit","Viel Klarheit"],
    ["Kurzfristige Wirkung","Langfristige Wirkung"],
    ["Wenig Essen","Viel Essen"],
    ["Wenig Druckluft","Viel Druckluft"],
    ["Kleines Publikum","Großes Publikum"],
    ["Wenig Interesse","Viel Interesse"],
    ["Wenig Vertrauen","Viel Vertrauen"],
    ["Wenig Mut","Viel Mut"],
    ["Langsam reagierend","Schnell reagierend"],
    ["Geringe Breite","Große Breite"],
    ["Wenig Würze","Viel Würze"],
    ["Wenig Schärfe","Viel Schärfe"],
    ["Wenig Energie","Viel Energie"],
    ["Niedrige Priorität","Hohe Priorität"],
    ["Wenig Licht","Viel Licht"],
    ["Wenig Geschmack","Viel Geschmack"],
    ["Wenig Wärme","Viel Wärme"],
    ["Wenig Hoffnung","Viel Hoffnung"],
    ["Wenig Elastizität","Viel Elastizität"],
    ["Wenig Feuchtigkeit","Viel Feuchtigkeit"],
    ["Wenig Stärke","Viel Stärke"],
    ["Minimale Bewegung","Maximale Bewegung"],
    ["Geringer Lärm","Hoher Lärm"],
    ["Wenig Technik","Viel Technik"],
    ["Wenig Kunst","Viel Kunst"],
    ["Wenig Strategie","Viel Strategie"],
    ["Kurzes Ereignis","Langes Ereignis"],
    ["Wenig Spannung","Viel Spannung"],
    ["Minimaler Aufwand","Maximaler Aufwand"],
    ["Wenig Vorbereitung","Viel Vorbereitung"],
    ["Wenig Erfahrung","Viel Erfahrung"],
    ["Wenig Würze","Viel Würze"],
    ["Wenig Fantasie","Viel Fantasie"],
    ["Wenig Ordnung","Viel Ordnung"],
    ["Wenig Chaos","Viel Chaos"],
    ["Wenig Risiko","Viel Risiko"],
    ["Wenig Abwechslung","Viel Abwechslung"],
    ["Wenig Struktur","Viel Struktur"],
    ["Wenig Aufmerksamkeit","Viel Aufmerksamkeit"],
    ["Wenig Intelligenz","Viel Intelligenz"],
    ["Wenig Farbe","Viel Farbe"],
    ["Wenig Geduld","Viel Geduld"],
    ["Wenig Ehrgeiz","Viel Ehrgeiz"],
    ["Wenig Glanz","Viel Glanz"],
    ["Wenig Freude","Viel Freude"],
    ["Wenig Tempo","Viel Tempo"],
    ["Wenig Fantasie","Viel Fantasie"],
    ["Wenig Intensität","Viel Intensität"],
];
